#!/bin/bash
# for core files in case you want to debug
ulimit -c unlimited

# malloc() built-in heap corruption detection
#export MALLOC_CHECK_=1

./pandora -c ./configs/mume.xml

# Use this one for MUD Emulation mode
#./pandora -e -c ./configs/mume.conf

